#Storing passwords in a Kubernetes Secret instead of code (e.g., password=123456) allows MySQL to securely read them via env: valueFrom: secretKeyRef

kind: Secret
apiVersion: v1
metadata:
  name: mysql-secret
type: Opaque
#The term implies that Kubernetes doesn't need to "see" or understand the structure of the data to use it. It simply stores the key-value pairs and hands them to your Pod when requested.

stringData:
  MYSQL_PASSWORD: Zpqmal@73
